/robot_news_station_giskard:
  ros__parameters:
    robot_name: "giskard"

/robot_news_station_bb8:
  ros__parameters:
    robot_name: "bb8"

/robot_news_station_daneel:
  ros__parameters:
    robot_name: "daneel"

/robot_news_station_lander:
  ros__parameters:
    robot_name: "lander"

/robot_news_station_c3po:
  ros__parameters:
    robot_name: "c3po"